### ISSUE TITLE
seems not working on gnome 3.6

### ISSUE THREAD

**Issue by iamdey** [franziskuskiefer/app-keys-gnome-shell-extension#13]
First, this is the extension I was looking for, thanks for making it.

But nothing happend when I press `<super> <num>/<numpad>/<shift>...  `
Acyually I'm stuck on gnome-shell 3.6.3.1 at work.
The extension is activated and all config entries are enabled. This is the only one extension I have.
I have some apps in favorite. I have a french flavor keyboard.

I don't know gnome API but I know some javascript.
How can I debug your extension ?
Did I missed something ?

**Comment by franziskuskiefer** [comment]
can you tell me if there are any error messages? The fastest way to check that is `ALT+F2`, type `lg` and press enter. Check in the extensions tab if there are errors (`Show Errors`) for this extension.

I currently don't have a working GS 3.6, but I try looking into it. The keyboard layout shouldn't play a role here.

**Comment by esion** [comment]
sorry for the latency. Well, there's no errors 

Also I tried to add some console.log() in the code but nothing appears. (may I have to restart my session?)

**Comment by esion** [comment]
By the way the extension works great on my own computer (gnome-shell v3.12). 

If nobody else is affected, I will understand you put the tag "won't fix". 
My office computer must be upgraded some day (I am on an old and unmaintained version of ubuntu). So I can go back to unity until I've migrated my OS.

**Comment by franziskuskiefer** [comment]
Unfortunately I currently don't have much time to look into this, but I'll do as soon as possible.

If you want to debug it yourself, you always have to restart GS (`ALT+F2`, `r`) for changes to take effect. You can also have a look at older versions of the extension (I'm pretty sure it worked with 3.6 at some point) and see where it breaks (for example https://extensions.gnome.org/review/4253).

**Comment by esion** [comment]
thank you
