### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by dpavlic** [franziskuskiefer/app-keys-gnome-shell-extension#16]
Hi all,

Has anyone had a problem where the extension stops working? I've yet to isolate the problem, but it occurs in Gnome 3.16 on my Fedora 22 box. I've turned off all other extensions but it still occurs. Wiping the extension completely, and then re-enabling it seems to work but a simple OFF / ON will not. Anyone else? It's so difficult to work with GNOME without.

**Comment by franziskuskiefer** [comment]
do you have any log or any specifics on it? I don't have any problems (Arch GS 3.16).

**Comment by dpavlic** [comment]
Annoyingly, I can't replicate the behaviour at all now, after experiencing it two times. Searching the x errors shows no errors for appkeys. I'm going to close this down for now, and reopen if it happens again and I can find something useful in the logs.

**Comment by dpavlic** [comment]
Quick update: this is an issue with Dash to Dock. Disabling Dash to Dock doesn't actually get rid of whatever the issue is in the D2D code (as xsession errors made evident). Restarting gnome shell with D2D disabled fixes the issue. The good news is it has nothing to do with appkeys.
