### ISSUE TITLE
Multiple presses of Super+<num> should cycle instances

### ISSUE THREAD

**Issue by ccoenen** [franziskuskiefer/app-keys-gnome-shell-extension#18]
On Windows, <kbd>Win+Number</kbd> cycles the open windows for a group. More specifically, if i open 3 seperate windows of firefox, and it sits in the fifth spot of my Task bar, I can use <kbd>Win+5</kbd> to get to the first firefox window. If i keep pressing <kbd>Win</kbd> and hit <kbd>5</kbd> many times, i can choose which window, exactly, Press <kbd>5</kbd> two times to get the second window, press it three times to get to the third... you get the picture.

I find this immensely useful. It's like a focused form of <kbd>Alt+Tab</kbd>. Is there any chance that this could be integrated into AppKeys?

**Comment by DoctorJellyface** [comment]
+1

**Comment by franziskuskiefer** [comment]
yeah that sounds like a good feature. I have to see when I find time to do it. Pull requests are also appreciate ;)

**Comment by bosyi** [comment]
+1

**Comment by franziskuskiefer** [comment]
Thanks for the PR bosyi franziskuskiefer/app-keys-gnome-shell-extension#22
