### ISSUE TITLE
Support for Gnome 3.18

### ISSUE THREAD

**Issue by ainola** [franziskuskiefer/app-keys-gnome-shell-extension#19]
3.18 is in RC state and is due for release very soon.

Thanks for the wonderful extension.

**Comment by franziskuskiefer** [comment]
did anyone test this on 3.18 yet? I'm happy to enable it for 3.18 if it's working but can't test myself before it reached Arch.

**Comment by gergelypolonkai** [comment]
I have just upgraded to the RC, it seems to work fine with it (3.17.92), without any modifications (except `metadata.json` update.
