### ISSUE TITLE
Cycle windows do not work with multiple workspaces.

### ISSUE THREAD

**Issue by bosyi** [franziskuskiefer/app-keys-gnome-shell-extension#26]
and i am going to fix that)
Do we need something like:
win + key -> cycle through windows in active workspace,
win + ctrl(or some other key) + key -> cycle through windows in all workspaces?
Or vice versa, depending on 'Cycle Windows on Active Workspace' is true or false.

**Comment by franziskuskiefer** [comment]
Are you sure it's not working? The latest version introduced a pref to disable the cycling over multiple windows. Maybe that's disabled?

**Comment by bosyi** [comment]
Nope. It's not working and never worked. If you disable 'Cycle Windows on Active Workspace' and open windows of one application on several workspaces and try to switch(cycle) them you will see that.
I researching now best way to fix that.

**Comment by nicman23** [comment]
This is still an issue. In 3.20 (arch) if you are in a different workspace and you select a window you will only get a notification that "the window is ready"

**Comment by franglais125** [comment]
I committed patch 74d1701e214d934b71311a776b65d6f4b474d039 to fix this issue. It is working well for me on Gnome 3.20. Can somebody else confirm? @nicman23 , @bosyi ?
In that patch, only Line 69 is needed. The change is Line 71 is only to keep consistency in that if-else combo.
If it works for you, I can create a PR.

**Comment by bosyi** [comment]
At this moment it works as not expected for me. Try to open 3 windows of one app in workspace 1, and 1 window of same app in workspace 2, and cycle them.
Ehh. Dash to dock somehow fixed that problem, but they have a lot of code. Also they have "smart" cycling. Easiest way is to add click handlers to their app. Or investigate how they solve problem.

**Comment by franglais125** [comment]
@bosyi Sorry, it isn't clear to me: did you try using the patch I mentioned?

**Comment by bosyi** [comment]
Yep, I tried. Did you try to play with 4 windows?)
24 трав. 2016 07:36 "franglais125" <notifications@github.com> пише:

**Comment by franglais125** [comment]
Ah, ok, I see what you mean. I thought you meant it wasn't working at all...

With that patch it goes back and forth between the workspaces. A bit annoying.

**Comment by franglais125** [comment]
@bosyi ok! So I ported the relevant code from Dash-to-dock:
7fc54c07ab2758a424309b917bb73a63a282effb

Is it better now?

**Comment by nicman23** [comment]
I think so, will report back if i find anyways that breaks it. Thanks a lot :)

**Comment by franglais125** [comment]
@nicman23 @bosyi
Any news on this? If it is working well for you (without regressions) I can clean up the code and propose a PR. Let me know how it goes

**Comment by bosyi** [comment]
@franglais125 
Tried it now. Very good. Now it cycles "smart" and work with multiple workspaces good.
I hope @franziskuskiefer  will merge your PR with master.
Now you may look at https://github.com/franziskuskiefer/app-keys-gnome-shell-extension/issues/21 :)
Golden reference for that is build in Windownavigator extension.

**Comment by franglais125** [comment]
Heh, yeah, I've been wanting to work on that for some time now... I don't have the time yet.

**Comment by franziskuskiefer** [comment]
sorry for the delay. I merged the PR and will upload a new version to extensions.gnome.org soon
