### ISSUE TITLE
3.20 support?

### ISSUE THREAD

**Issue by ainola** [franziskuskiefer/app-keys-gnome-shell-extension#27]
Thanks so much for your invaluable extension. It'd be great if it were updated to 3.20!

**Comment by franziskuskiefer** [comment]
@ainola does the extension work when adding 3.20 in metadata.json? I'm still on 3.18 so can't test.

**Comment by ainola** [comment]
Yep, it works by just adding it.

**Comment by franziskuskiefer** [comment]
added 3.20 in https://github.com/franziskuskiefer/app-keys-gnome-shell-extension/commit/663f3133fc1d4ba2e53cc3845b7db81b5197dc3f
