### ISSUE TITLE
No Nautilus window is created when displaying icons on Dekstop

### ISSUE THREAD

**Issue by franglais125** [franziskuskiefer/app-keys-gnome-shell-extension#31]
Test case:

1) Have Nautilus be a favorite App (no windows open)
2) Use icons on desktop
3) Try to open Nautilus using Sup + Num -> focus seems lost

It will actually work if using Shif + Sup + Num.

I am preparing a fix for this.

**Comment by franglais125** [comment]
Here is the patch.
https://github.com/franglais125/app-keys-gnome-shell-extension/commit/1144cae33feb6c02d4d2e9e0a1403832a78ca196

**Comment by franziskuskiefer** [comment]
I merged PR #30 that includes this change and submitted it to http://extensions.gnome.org/. If it fixes this an #28, please close them.

**Comment by franglais125** [comment]
Thank you!

I will close this one, and wait to see if there is any activity on #28 in the next few days. The person who reported the bug didn't give any news, so I'm unsure if these commits fix his/her problem.
