### ISSUE TITLE
Can't install in Fedora 25 (GNOME 3.22)

### ISSUE THREAD

**Issue by okungnyo** [franziskuskiefer/app-keys-gnome-shell-extension#34]
I thought maybe it was just me, but there is at least one other person who is also experiencing this issue, and he/she has suggested that I report it here: https://www.reddit.com/r/Fedora/comments/5eycyo/anyone_else_have_trouble_installing_the_appkeys/

**Comment by Alxe** [comment]
The #33 PR landed three days ago, bumping the current version to 3.22, so my guess is that extensions.gnome.org didn't update from the repo or the dev has something to do manually.

I am too using Fedora if that means anything.

**Comment by franziskuskiefer** [comment]
I'll upload the new version as soon as extensions.gnome.org accepts uploads again. Their servers appear to be broken.

**Comment by franziskuskiefer** [comment]
The version on extensions.gnome.org is updated.
