### ISSUE TITLE
Extension breaks with gnome-shell 3.30 

### ISSUE THREAD

**Issue by eddy-geek** [franziskuskiefer/app-keys-gnome-shell-extension#43]
Extension does not start on Fedora 29 Beta, gnome-shell 3.30 RC (3.29.91-1). I will submit a PR to fix this.

## Current Behavior
Following error is printed:

    (gnome-shell:32163): Gjs-WARNING **: 21:25:57.923: JS ERROR: TypeError: global.screen is undefined
    AppKeys.prototype.clickClosure/<@/home/eoubrayrie/.local/share/gnome-shell/extensions/unitylike-hotkey@webgyerek.net/extension.js:59:13

## Solution
See https://github.com/home-sweet-gnome/dash-to-panel/issues/434 and fix https://github.com/micheleg/dash-to-dock/pull/770

> Basically global.screen moved to global.display, while all the workspace related features have been moved to the WorkspaceManager and displays are managed by DisplayManager.

Also the built-in extensions update [commit](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/commit/6583eae6225039b6b711918eff3a7cd0d03a42ca).

## Your Environment
* gnome-shell version: 3.29.91-1
* distribution : Fedora 29 Beta

**Comment by ambiso** [comment]
When will this be released to https://extensions.gnome.org/extension/413/dash-hotkeys/ ?

**Comment by franziskuskiefer** [comment]
I'll do a release soonish. Didn't get around to it yet.
