### ISSUE TITLE
cannot enable under gnome-shell 3.36.7

### ISSUE THREAD

**Issue by jesteria** [franziskuskiefer/app-keys-gnome-shell-extension#52]
(Among a number of other extensions), AppKeys appears disabled by gnome-shell 3.36.7.

I've tried reinstalling the extension (v21), and it installs, but it cannot be enabled.

**Comment by franziskuskiefer** [comment]
I didn't look at this in a while... Do you have some debug/error output or anything?

**Comment by jesteria** [comment]
It seems pop-os had disabled nearly all of my extensions, and I had to do …something … to re-enable them. I'm not sure why. But … thanks! All good here.
